### ISSUE TITLE
Error in Test Case

### ISSUE THREAD

**Issue by mronian** [JuliaImages/ImageFeatures.jl#24]
As pointed out in https://github.com/JuliaImages/Images.jl/pull/601#issuecomment-284150087.

**Comment by mronian** [comment]
Are there other test failures too?

**Comment by timholy** [comment]
Sometimes you do have to change the test values when algorithms update. In https://github.com/JuliaImages/Images.jl/pull/596 I found a test that essentially "froze in" the exact behavior of the algorithm we'd had before, rather than more broadly testing "sensible behavior." The tricky part is that sometimes it's pretty hard to define "sensible."

@annimesh2809, I'd say begin by commenting out failing tests and then we can discuss.

**Comment by annimesh2809** [comment]
@mronian Sorry I did not see your comment so didn't reply sooner.

I have fixed some warnings and I have printed the value returned by the algorithm and the expected value of a test case.

![screenshot from 2017-03-04 19 44 37](https://cloud.githubusercontent.com/assets/15063205/23579431/01926852-0113-11e7-944a-5888042ba3af.png)

The failing test case is at line 55 of /test/brief.jl.
What to do with this test case?

**Comment by mronian** [comment]
Its a very simple test case which is already covered by the ones after it in the `Descriptor Calculation` part. You can comment it out for now. I'll submit a modification.

**Comment by annimesh2809** [comment]
Another failing test on line 253 and 259 of file /test/lbp.jl. Both the results of "Descriptor" are different from expected value. Here is a screenshot of the test failure and the returned vs expected value:

![img](https://cloud.githubusercontent.com/assets/15063205/23579970/bb41026c-011e-11e7-9ee5-a6abef05a4b4.png)

**Comment by annimesh2809** [comment]
Initial tests in test/corner.jl call the `corner_orientations(img::AbstractArray)` function from line 49, ImageFeatures/src/corner.jl. Here the function `Kernel.gaussian` (previously `gaussian2d`) is called from line 134, ImageFiltering/src/kernel.jl which calls `KernelFactors.gaussian` from line 269, ImageFiltering/kernelfactors.jl and returns an object of type `OffsetArray` by a call to `centered` from line 14, ImageFiltering/src/utils.jl. The problem arises due to the fact that the function
`corner_orientations(img::AbstractArray{T, 2}, corners::Keypoints, kernel::Array{K, 2})`
(Line 16, ImageFeatures/src/corner.jl) which is called after creating the kernel by the above process must have `kernel` of type `Array{K,2}` but the kernel is of type `OffsetArray`. Hence a MethodError occurs:

![img2](https://cloud.githubusercontent.com/assets/15063205/23580665/ee0fd422-012b-11e7-936a-0de9b525732a.png)

Should I write a function to convert the `OffsetArray` to `Array{K,2}` in `corner_orientations` or should I write another version of `centered` function to return an `Array` instead of `OffsetArray`? Please suggest.

**Comment by timholy** [comment]
The most expedient approach is to call `parent` on the `OffsetArray`; that will return a conventionally-indexed array. In the longer run, non-1 indices allow you to express filtering operations easily with clearer intent; there's a WIP blog post [here](https://github.com/JuliaLang/julialang.github.com/pull/498).

**Comment by annimesh2809** [comment]
All warnings have been removed. Only 4 failing test cases remain.  :smile: 

![al_su](https://cloud.githubusercontent.com/assets/15063205/23581645/a1f8ee54-013d-11e7-84cd-c454dff1b3c9.png)

**Comment by annimesh2809** [comment]
Only 2 test case failures remain which are present in LBP as mentioned in https://github.com/JuliaImages/ImageFeatures.jl/issues/24#issuecomment-284159185. These tests cannot be removed as it can lead to decrease in coverage. Kindly suggest what to do.

**Comment by annimesh2809** [comment]
I commented out the 2 failing test cases and then tried doing a coverage test but travis failed stating that some tests were taking too much time. Indeed the tests for "orb.jl" were taking too much time (> 30 mins) so I commented that too and got a coverage of about 88%, with all orb.jl tests and some lbp.jl tests turned off.
https://coveralls.io/github/annimesh2809/ImageFeatures.jl

Should I remove the "Descriptor" tests of lbp that are failing for now?
