### ISSUE TITLE
Is it on the roadmap to support 1.0 in the near feature 

### ISSUE THREAD

**Issue by gzhang8** [JuliaImages/ImageFeatures.jl#53]
Right now it doesn't work with 1.0, yet I don't see much activity here. Any plan to support 1.0?
```
julia> using ImageFeatures
[ Info: Precompiling ImageFeatures [92ff4b2b-8094-53d3-b29d-97f740f06cef]
ERROR: LoadError: LoadError: syntax: invalid escape sequence
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include at ./sysimg.jl:29 [inlined]
 [4] include(::String) at /home/gzhang8/.julia/packages/ImageFeatures/0YxwE/src/ImageFeatures.jl:3
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:389
 [12] top-level scope at ./none:3

```

**Comment by timholy** [comment]
At the moment my priorities are ImageView and Interpolations. I am sure someone will get to it, but that someone could be you! If you want to give it a whirl, I recommend installing Julia 0.7 since you'll get deprecation warnings that will tell you how to change the code.

**Comment by gzhang8** [comment]
This is error is due to `    `x \* cos(t) + y \* sin(t) = r`
 `https://github.com/JuliaImages/ImageFeatures.jl/blob/master/src/houghtransform.jl#L10

What is the reason that `*` needs to be escaped? What is the new way to escape?

**Comment by zygmuntszpak** [comment]
@timholy Could you please clarify how we should proceed with the 1.0 upgrade? Do we just merge the required fixed with the master branch and then tag a release? Anyone who wants to use 0.6.4 would then need to checkout the previous version?  

(I didn't mean to close the issue...accidental misclick)

**Comment by Evizero** [comment]
With the 0.7 fixes you would also bump the minimum julia version in REQUIRE to 0.7 and then tag. 
As a consequence every 0.6 user who `Pkg.add` this package would only install the latest version that supported 0.6 in its REQUIRE, while everyone on 0.7 and later would install the newer version

**Comment by timholy** [comment]
General procedure:
- open a pull request where you just set `REQUIRE` to have `julia 0.7` as a minimum requirement
- wait for femtocleaner to submit a pull request that fixes the "obvious" issues. If it looks good merge to your branch
- fix remaining errors and deprecations from building the package and/or running the tests
- if needed include at least versions 0.7, 1.0, and nightly in the .travis.yml and/or appveyor.yml tests
- once tests pass, merge to master
- tag a new release bumping the minor version

However, I see that a couple of PRs have been submitted while I was out. If there is anything any of the folks with commit access can do to check those over and see if they are mergeable (or close to it), that would be a huge help. It would be nice to get that done before starting on the 0.7 upgrade, so that people's work isn't left out in the cold. (This is only applicable if the PRs are close to being mergeable.)

**Comment by timholy** [comment]
Oh, I see @gzhang8 has already been working on this! :+1: Well, we can always migrate people's PRs for them, so don't let me stand in the way of progress :smile:.

**Comment by gzhang8** [comment]
https://github.com/JuliaImages/ImageFeatures.jl/pull/56
